#!/usr/bin/env bash
# Packages the SPM release build into a self-contained .app bundle
# and ad-hoc signs it for local use.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
APP="$REPO/WhisperInput.app"
MACOS="$APP/Contents/MacOS"
RESOURCES="$APP/Contents/Resources"

echo "→ Packaging WhisperInput.app"

# Directories
mkdir -p "$MACOS" "$RESOURCES"

# Binary (SPM names it WhisperInputMain; the bundle expects WhisperInput)
cp "$REPO/.build/release/WhisperInputMain" "$MACOS/WhisperInput"
chmod +x "$MACOS/WhisperInput"

# SPM resources bundle (PrivacyInfo + Localizable.strings)
cp -r "$REPO/.build/release/WhisperInput_WhisperInput.bundle" "$RESOURCES/"

# App icon (generated by scripts/generate-icon.swift, created once)
ICNS="$RESOURCES/AppIcon.icns"
if [ ! -f "$ICNS" ]; then
  echo "  → Generating placeholder icon…"
  "$REPO/scripts/generate-icon.sh"
fi

# Info.plist is already in the bundle — nothing to copy.
# Ad-hoc codesign: lets the app run locally without a Developer ID.
# Replace '-' with your Developer ID for distribution.
codesign --force --deep --sign - "$APP" 2>/dev/null

echo "✓ WhisperInput.app is ready"
